# Generated by Django 4.1.1 on 2024-10-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obligacionfinanciera',
            name='usuario',
        ),
        migrations.AddField(
            model_name='prediccionfinanciera',
            name='decision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediccionfinanciera',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediccionfinanciera',
            name='recomendacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediccionfinanciera',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.categoriagasto'),
        ),
        migrations.DeleteModel(
            name='GastoOperativo',
        ),
        migrations.DeleteModel(
            name='ObligacionFinanciera',
        ),
    ]
