# Generated by Django 4.1.1 on 2025-04-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_obligacionfinanciera_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaegreso',
            options={'verbose_name_plural': 'Obligaciones Financieras'},
        ),
        migrations.AddField(
            model_name='metaegreso',
            name='tipogasto',
            field=models.CharField(choices=[('F', 'Fijo'), ('V', 'Variable')], default='V', max_length=1),
        ),
        migrations.DeleteModel(
            name='ResultadoPrediccion',
        ),
    ]
